spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8010/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

server:
  port: 8020

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

